services:
  db:
    image: postgres:16.0
    restart: always
    container_name: preparo-postgres
    ports:
      - "5401:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    networks:
      - default

volumes:
  m2-repo:



